# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-28 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pre_friend',
            field=models.ManyToManyField(related_name='_userinfo_pre_friend_+', to='app01.UserInfo', verbose_name='好友请求'),
        ),
    ]
