# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-28 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180528_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='pre_friend',
        ),
        migrations.AddField(
            model_name='user2user',
            name='u_receiveReq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans_user', to='app01.UserInfo'),
        ),
        migrations.AddField(
            model_name='user2user',
            name='u_sendReq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fans', to='app01.UserInfo'),
        ),
    ]
