# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-28 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180528_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2user',
            name='u_receiveReq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_sends', to='app01.UserInfo'),
        ),
        migrations.AlterField(
            model_name='user2user',
            name='u_sendReq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_receives', to='app01.UserInfo'),
        ),
    ]
