# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-01 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20180528_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='user2user',
            name='u_receiveReq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_sends', to='app01.UserInfo', verbose_name='接收者'),
        ),
        migrations.AlterField(
            model_name='user2user',
            name='u_sendReq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_receives', to='app01.UserInfo', verbose_name='发送者'),
        ),
    ]
